export const CITY_DISTRICTS = {
  Erbil: [
    "Hawler",
    "Soran",
    "Shaqlawa",
    "Mergasor",
    "Choman",
    "Koye",
    "Rwanduz",
    "Dashti Hawler",
  ],
  Sulaimani: [
    "Slemani",
    "Bazyan",
    "Penjwen",
    "Qaradax",
    "Sharbazher",
    "Dukan",
    "Ranya",
    "Pashadar",
    "Penjwin",
    "Chemchemal",
  ],
  Duhok: [
    "Duhok",
    "Akre",
    "Zakho",
    "Amadiya",
    "Simele",
    "Bardarash",
    "Shekhan",
  ],
  Halabja: ["Halbja", "Khurmal", "Byara", "Tawella"],
};
